manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: wang-public
      url-base: https://github.com/DoctorWangWang

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      path: zmk

    - name: zmk-pmw3610-driver
      remote: wang-public
      revision: main

  self:
    path: config
