manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: DoctorWangWang
      url-base: https://github.com/DoctorWangWang

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.1

    - name: zmk-pmw3610-drive
      remote: DoctorWangWang
      revision: main

  self:
    path: config
